[project]
name = "shiny-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "maplibre>=0.2.7",
    "shiny>=1.2.1",
]
